### PR TITLE
Master

### PR DESCRIPTION
**Pull request by radeklos**
Merge down some hotfixes

### CODE REVIEW

**Comment by krak3n** [comment]
Hasn't this already been merged?

**Comment by radeklos** [comment]
Elapsed time bugfix hasn't but it's weird that your commits are in there as well..

**Comment by krak3n** [comment]
You PR'd #31 into `master`, its already been deployed.

**Comment by krak3n** [comment]
Ah ignore me this is `master` into `develop`

**Comment by krak3n** [comment]
:+1:

**Pull request merged**
