### PR TITLE
Feature: Track User Storage

### PR DESCRIPTION
**Pull request by krak3n**
This PR will now store the user against the playlist entry. The following resources have been updated to contain the user and track data:

* `/player/queue`
* `/player/current`

All other resources and events remain the same.

The resources will now provided data in the following format:

``` json
{
    "track": {
        "album": {
            "id": "97379e23-f679-45c2-8e4f-730ae16b8ab1",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/770cfef8e832ae47139debe788f7c11afb92a816",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/dcb8f435712888a71f4106b1ed83da9e6713e1e0",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/8a87ca6a9fc52e63c1c69f32d14c9bbec2ac0e77",
                    "width": 64
                }
            ],
            "name": "Devotion",
            "uri": "spotify:album:5SpcwnEVClk33l5QM04vSy"
        },
        "artists": [
            {
                "id": "5869f551-8046-4351-9154-05390cf7d19d",
                "name": "Anberlin",
                "uri": "spotify:artist:5v61OSg53KaQxGMpErkBNp"
            }
        ],
        "duration": 201806,
        "id": "37cf2599-e260-4d96-b49d-b3a96a6c9e24",
        "name": "Little Tyrants",
        "play_count": 1,
        "uri": "spotify:track:11oRv2sfZJxNYqCl6wLaqJ"
    },
    "user": {
        "avatar_url": "http://ijoyvd.jpg",
        "display_name": "jmOrBO",
        "family_name": "UNnJkKLr",
        "given_name": "ijoyvd",
        "id": "de03ce58-c6cf-4934-9a32-cd3c611e0179"
    }
}
```

This will require changes by the FE.

### CODE REVIEW

**Comment by krak3n** [comment]
cc/ @eopa & @jamesjwarren

**Comment by jamesjwarren** [comment]
I'll look at implementing this now.

**Comment by krak3n** [comment]
@jamesjwarren user data snippet example:

``` json
"user" {
    "avatar_url": "https://lh5.googleusercontent.com/-8zjhd-e4yZA/AAAAAAAAAAI/AAAAAAAAAFU/NiS1oH4gAKo/photo.jpg",
    "display_name": "Chris Reeves",
    "family_name": "Reeves",
    "given_name": "Chris",
    "id": "8258be6b-ee53-4186-8bbd-55bc0a3a6f24"
}
```

**Comment by krak3n** [comment]
Updated to contain full JSON example response

**Comment by jamesjwarren** [comment]
:+1:

**Pull request merged**
