### PR TITLE
Release: 2015-07-31

### PR DESCRIPTION
**Pull request by jamesjwarren**
# 2015-07-31
- Feature: track analysis from echnoest
- Fix: Remove trailing slash from user/:id/stats resource
- Fix: Remove slash from queue endpoint
- Feature: Delete track from the queue
- Feature: User stats
- Feature: Add album

### CODE REVIEW

**Comment by jamesjwarren** [comment]
@krak3n / @radeklos everyone cool with merging this so we can deploy?

**Comment by radeklos** [comment]
I'm happy I just created this PR which I would like to have in release as well.. https://github.com/thisissoon/FM-API/pull/64

**Comment by krak3n** [comment]
@radeklos if you still have the branch re pull request it into this release branch

**Comment by radeklos** [comment]
I've merged redis change in.

**Comment by krak3n** [comment]
Cool, lets deployz tomorrow :smile:

**Comment by krak3n** [comment]
lol 7 days later

:trollface:

**Comment by edwardoparearyee** [comment]
@krak3n did this ever get pushed live?

**Pull request merged**
