### PR TITLE
Push latest docker container when something is merged into dev

### PR DESCRIPTION
**Pull request by radeklos**
Push container build from develop branch to docker hub.

### CODE REVIEW

**Comment by radeklos** [comment]
@krak3n @peeklondon CR please.

**Comment by krak3n** [comment]
@radeklos can I be annoying and change the tags so they align with whats in our Handbook.

So master = prod, develop = latest - we will also need to alter the salt states, if you fancy having a go at that?

**Comment by radeklos** [comment]
it's fine I can take a look on salt.. :)

**Comment by radeklos** [comment]
@krak3n I've fixed the docker tags.

**Comment by krak3n** [comment]
:bow:

**Pull request merged**
